// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ip-rw/ransack/ent/ip"
	"github.com/ip-rw/ransack/ent/machine"
	"github.com/ip-rw/ransack/ent/predicate"
)

// IPUpdate is the builder for updating IP entities.
type IPUpdate struct {
	config
	hooks    []Hook
	mutation *IPMutation
}

// Where adds a new predicate for the IPUpdate builder.
func (iu *IPUpdate) Where(ps ...predicate.IP) *IPUpdate {
	iu.mutation.predicates = append(iu.mutation.predicates, ps...)
	return iu
}

// SetIP sets the "ip" field.
func (iu *IPUpdate) SetIP(s string) *IPUpdate {
	iu.mutation.SetIP(s)
	return iu
}

// SetNet sets the "net" field.
func (iu *IPUpdate) SetNet(s string) *IPUpdate {
	iu.mutation.SetNet(s)
	return iu
}

// SetMask sets the "mask" field.
func (iu *IPUpdate) SetMask(i int) *IPUpdate {
	iu.mutation.ResetMask()
	iu.mutation.SetMask(i)
	return iu
}

// SetNillableMask sets the "mask" field if the given value is not nil.
func (iu *IPUpdate) SetNillableMask(i *int) *IPUpdate {
	if i != nil {
		iu.SetMask(*i)
	}
	return iu
}

// AddMask adds i to the "mask" field.
func (iu *IPUpdate) AddMask(i int) *IPUpdate {
	iu.mutation.AddMask(i)
	return iu
}

// SetMachineID sets the "machine" edge to the Machine entity by ID.
func (iu *IPUpdate) SetMachineID(id int) *IPUpdate {
	iu.mutation.SetMachineID(id)
	return iu
}

// SetNillableMachineID sets the "machine" edge to the Machine entity by ID if the given value is not nil.
func (iu *IPUpdate) SetNillableMachineID(id *int) *IPUpdate {
	if id != nil {
		iu = iu.SetMachineID(*id)
	}
	return iu
}

// SetMachine sets the "machine" edge to the Machine entity.
func (iu *IPUpdate) SetMachine(m *Machine) *IPUpdate {
	return iu.SetMachineID(m.ID)
}

// Mutation returns the IPMutation object of the builder.
func (iu *IPUpdate) Mutation() *IPMutation {
	return iu.mutation
}

// ClearMachine clears the "machine" edge to the Machine entity.
func (iu *IPUpdate) ClearMachine() *IPUpdate {
	iu.mutation.ClearMachine()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *IPUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iu.hooks) == 0 {
		affected, err = iu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IPMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iu.mutation = mutation
			affected, err = iu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iu.hooks) - 1; i >= 0; i-- {
			mut = iu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IPUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IPUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IPUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *IPUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ip.Table,
			Columns: ip.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ip.FieldID,
			},
		},
	}
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.IP(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ip.FieldIP,
		})
	}
	if value, ok := iu.mutation.Net(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ip.FieldNet,
		})
	}
	if value, ok := iu.mutation.Mask(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: ip.FieldMask,
		})
	}
	if value, ok := iu.mutation.AddedMask(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: ip.FieldMask,
		})
	}
	if iu.mutation.MachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ip.MachineTable,
			Columns: []string{ip.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: machine.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.MachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ip.MachineTable,
			Columns: []string{ip.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: machine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ip.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// IPUpdateOne is the builder for updating a single IP entity.
type IPUpdateOne struct {
	config
	hooks    []Hook
	mutation *IPMutation
}

// SetIP sets the "ip" field.
func (iuo *IPUpdateOne) SetIP(s string) *IPUpdateOne {
	iuo.mutation.SetIP(s)
	return iuo
}

// SetNet sets the "net" field.
func (iuo *IPUpdateOne) SetNet(s string) *IPUpdateOne {
	iuo.mutation.SetNet(s)
	return iuo
}

// SetMask sets the "mask" field.
func (iuo *IPUpdateOne) SetMask(i int) *IPUpdateOne {
	iuo.mutation.ResetMask()
	iuo.mutation.SetMask(i)
	return iuo
}

// SetNillableMask sets the "mask" field if the given value is not nil.
func (iuo *IPUpdateOne) SetNillableMask(i *int) *IPUpdateOne {
	if i != nil {
		iuo.SetMask(*i)
	}
	return iuo
}

// AddMask adds i to the "mask" field.
func (iuo *IPUpdateOne) AddMask(i int) *IPUpdateOne {
	iuo.mutation.AddMask(i)
	return iuo
}

// SetMachineID sets the "machine" edge to the Machine entity by ID.
func (iuo *IPUpdateOne) SetMachineID(id int) *IPUpdateOne {
	iuo.mutation.SetMachineID(id)
	return iuo
}

// SetNillableMachineID sets the "machine" edge to the Machine entity by ID if the given value is not nil.
func (iuo *IPUpdateOne) SetNillableMachineID(id *int) *IPUpdateOne {
	if id != nil {
		iuo = iuo.SetMachineID(*id)
	}
	return iuo
}

// SetMachine sets the "machine" edge to the Machine entity.
func (iuo *IPUpdateOne) SetMachine(m *Machine) *IPUpdateOne {
	return iuo.SetMachineID(m.ID)
}

// Mutation returns the IPMutation object of the builder.
func (iuo *IPUpdateOne) Mutation() *IPMutation {
	return iuo.mutation
}

// ClearMachine clears the "machine" edge to the Machine entity.
func (iuo *IPUpdateOne) ClearMachine() *IPUpdateOne {
	iuo.mutation.ClearMachine()
	return iuo
}

// Save executes the query and returns the updated IP entity.
func (iuo *IPUpdateOne) Save(ctx context.Context) (*IP, error) {
	var (
		err  error
		node *IP
	)
	if len(iuo.hooks) == 0 {
		node, err = iuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IPMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iuo.mutation = mutation
			node, err = iuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(iuo.hooks) - 1; i >= 0; i-- {
			mut = iuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IPUpdateOne) SaveX(ctx context.Context) *IP {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *IPUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IPUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *IPUpdateOne) sqlSave(ctx context.Context) (_node *IP, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ip.Table,
			Columns: ip.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ip.FieldID,
			},
		},
	}
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing IP.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.IP(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ip.FieldIP,
		})
	}
	if value, ok := iuo.mutation.Net(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: ip.FieldNet,
		})
	}
	if value, ok := iuo.mutation.Mask(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: ip.FieldMask,
		})
	}
	if value, ok := iuo.mutation.AddedMask(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: ip.FieldMask,
		})
	}
	if iuo.mutation.MachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ip.MachineTable,
			Columns: []string{ip.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: machine.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.MachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ip.MachineTable,
			Columns: []string{ip.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: machine.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IP{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ip.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
