// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: pkg/proto/hash.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes []uint64 `protobuf:"varint,1,rep,packed,name=hashes,proto3" json:"hashes,omitempty"`
}

func (x *Hashes) Reset() {
	*x = Hashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashes) ProtoMessage() {}

func (x *Hashes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashes.ProtoReflect.Descriptor instead.
func (*Hashes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hash_proto_rawDescGZIP(), []int{0}
}

func (x *Hashes) GetHashes() []uint64 {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type DirectoryHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash uint64 `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *DirectoryHash) Reset() {
	*x = DirectoryHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectoryHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryHash) ProtoMessage() {}

func (x *DirectoryHash) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryHash.ProtoReflect.Descriptor instead.
func (*DirectoryHash) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hash_proto_rawDescGZIP(), []int{1}
}

func (x *DirectoryHash) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *DirectoryHash) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryHash) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LookupResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedHashes []uint64         `protobuf:"varint,1,rep,packed,name=requestedHashes,proto3" json:"requestedHashes,omitempty"`
	FoundHashes     []*DirectoryHash `protobuf:"bytes,2,rep,name=foundHashes,proto3" json:"foundHashes,omitempty"`
}

func (x *LookupResult) Reset() {
	*x = LookupResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResult) ProtoMessage() {}

func (x *LookupResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResult.ProtoReflect.Descriptor instead.
func (*LookupResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hash_proto_rawDescGZIP(), []int{2}
}

func (x *LookupResult) GetRequestedHashes() []uint64 {
	if x != nil {
		return x.RequestedHashes
	}
	return nil
}

func (x *LookupResult) GetFoundHashes() []*DirectoryHash {
	if x != nil {
		return x.FoundHashes
	}
	return nil
}

type DirectoryHashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirectoryHashes []*DirectoryHash `protobuf:"bytes,1,rep,name=directoryHashes,proto3" json:"directoryHashes,omitempty"`
}

func (x *DirectoryHashes) Reset() {
	*x = DirectoryHashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hash_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectoryHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryHashes) ProtoMessage() {}

func (x *DirectoryHashes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hash_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryHashes.ProtoReflect.Descriptor instead.
func (*DirectoryHashes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hash_proto_rawDescGZIP(), []int{3}
}

func (x *DirectoryHashes) GetDirectoryHashes() []*DirectoryHash {
	if x != nil {
		return x.DirectoryHashes
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Affected int64 `protobuf:"varint,2,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hash_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hash_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hash_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

var File_pkg_proto_hash_proto protoreflect.FileDescriptor

var file_pkg_proto_hash_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x73, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x20, 0x0a, 0x06,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x4b,
	0x0a, 0x0d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x6f, 0x0a, 0x0c, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52,
	0x0b, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x0f,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12,
	0x3d, 0x0a, 0x0f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x2e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0f, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x22, 0x3e,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x32, 0x67,
	0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x12, 0x0c, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x1a, 0x12,
	0x2e, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x12, 0x15, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x1a, 0x0c, 0x2e, 0x68, 0x61, 0x73, 0x68,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_hash_proto_rawDescOnce sync.Once
	file_pkg_proto_hash_proto_rawDescData = file_pkg_proto_hash_proto_rawDesc
)

func file_pkg_proto_hash_proto_rawDescGZIP() []byte {
	file_pkg_proto_hash_proto_rawDescOnce.Do(func() {
		file_pkg_proto_hash_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_hash_proto_rawDescData)
	})
	return file_pkg_proto_hash_proto_rawDescData
}

var file_pkg_proto_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_hash_proto_goTypes = []interface{}{
	(*Hashes)(nil),          // 0: hash.Hashes
	(*DirectoryHash)(nil),   // 1: hash.DirectoryHash
	(*LookupResult)(nil),    // 2: hash.LookupResult
	(*DirectoryHashes)(nil), // 3: hash.DirectoryHashes
	(*Result)(nil),          // 4: hash.Result
}
var file_pkg_proto_hash_proto_depIdxs = []int32{
	1, // 0: hash.LookupResult.foundHashes:type_name -> hash.DirectoryHash
	1, // 1: hash.DirectoryHashes.directoryHashes:type_name -> hash.DirectoryHash
	0, // 2: hash.Hash.Lookup:input_type -> hash.Hashes
	3, // 3: hash.Hash.SubmitHashes:input_type -> hash.DirectoryHashes
	2, // 4: hash.Hash.Lookup:output_type -> hash.LookupResult
	4, // 5: hash.Hash.SubmitHashes:output_type -> hash.Result
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_hash_proto_init() }
func file_pkg_proto_hash_proto_init() {
	if File_pkg_proto_hash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_hash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectoryHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hash_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectoryHashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hash_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_hash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_hash_proto_goTypes,
		DependencyIndexes: file_pkg_proto_hash_proto_depIdxs,
		MessageInfos:      file_pkg_proto_hash_proto_msgTypes,
	}.Build()
	File_pkg_proto_hash_proto = out.File
	file_pkg_proto_hash_proto_rawDesc = nil
	file_pkg_proto_hash_proto_goTypes = nil
	file_pkg_proto_hash_proto_depIdxs = nil
}
