// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IP is the predicate function for ip builders.
type IP func(*sql.Selector)

// Key is the predicate function for key builders.
type Key func(*sql.Selector)

// Machine is the predicate function for machine builders.
type Machine func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
